version: "3"

services:
  database:
    image: "postgres14" # use latest official postgres version
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_vue_go
    networks:
      - db_network
    volumes:
      - database-data:/var/lib/postgres/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

networks:
  db_network:
    driver: bridge

volumes:
  database-data: